### ISSUE TITLE
Recent Implementation

### ISSUE THREAD

**Issue by JBudzikowski** [leibo-cmu/MatSeg#1]
Hi! I am attempting to implement this on my own dataset and running into a lot of errors stemming from the packages themselves. I am wondering if the requirements.txt file had the proper packages a few years ago, but current versions of packages are not running properly with the program?  Would it be possible to obtain specified package versions for this code? For example, on error I received was fixed by installing an older version of torch (torch ==1.4.0), etc.

**Comment by lei-bo** [comment]
Hi, I'm sorry for the late reply. The codebase has a major update and I have specified the versions of multiple packages used in requirements.txt. Thanks for your interest in this work and let me know if you have further questions!
